name: state_management_experiment
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

workspace:
  - packages/state_management

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.5.3
  state_management:
    path: packages/state_management

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3

flutter:
  uses-material-design: true
